build: false

matrix:
  fast_finish: true

environment:
  matrix:
    - PYTHON: "C:\\miniconda3"

init:
  - "ECHO %PYTHON%"

install:
  # Cancel older builds for the same PR
  # Credits: JuliaLang developers
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Set up environment
  - set URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"
  - curl -fsS -o miniconda3.exe %URL%
  - start /wait "" miniconda3.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%PYTHON%
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - call %PYTHON%\Scripts\activate
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda config --set safety_checks disabled
  - conda config --set channel_priority strict
  - conda env create --file environment.yml
  - activate computational-publications
  - conda list
  - conda info --all

test_script:
  - conda list
  - conda list jupyter-book
